In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv("../veri_seti/insurance.csv")
data

age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [3]:
data.describe()

age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [7]:
expenses = data.expenses.values.reshape(-1,1)
ageBmis = data.iloc[:,[0,2]].values
ageBmis

array([[19. , 27.9],
       [18. , 33.8],
       [28. , 33. ],
       ...,
       [18. , 36.9],
       [21. , 25.8],
       [61. , 29.1]])

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
regression = LinearRegression()

In [11]:
regression.fit(ageBmis, expenses)

LinearRegression()

In [25]:
regression.predict([[50,20],[50,30]])

array([[12325.47330808],
       [15659.38186339]])

In [26]:
regression.predict([[40,20],[60,20]])

array([[ 9906.47257338],
       [14744.47404278]])