In [2]:
import numpy as np

In [3]:
havaDurumu = [12,21,31,5,7,13,21,12,10]
havaDurumu

[12, 21, 31, 5, 7, 13, 21, 12, 10]

In [10]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
a.shape

(15,)

In [12]:
type(a)

numpy.ndarray

In [14]:
a=a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
b.shape

(10,)

In [25]:
b.ndim

1

In [28]:
b.reshape(5,2).ndim # boyut n dimension

2