In [14]:
import numpy as np


In [15]:
a = np.array([2, 3, 5, 7, 9, 11, 13, 17, 19, 23, 29])
a


array([ 2,  3,  5,  7,  9, 11, 13, 17, 19, 23, 29])

In [16]:
a.dtype


dtype('int32')

In [17]:
a = np.array([2.3,3,5,7,9,11,13,17,19,23,29])
a

array([ 2.3,  3. ,  5. ,  7. ,  9. , 11. , 13. , 17. , 19. , 23. , 29. ])

In [18]:
a.dtype

dtype('float64')

In [19]:
a = np.array([2.3,3,5,"7",9,11,13,17,19,23,29])
a

array(['2.3', '3', '5', '7', '9', '11', '13', '17', '19', '23', '29'],
      dtype='<U32')

In [20]:
a.dtype

dtype('<U32')

In [26]:
b = np.array([
    [
        [11, 12, 13, 14],
        [21, 22, 23, 24],
        [31, 32, 33, 34]
    ],
    [
        [51, 52, 53, 54],
        [61, 62, 63, 64],
        [71, 72, 73, 74]
    ]
])


In [27]:
b.shape

(2, 3, 4)

In [28]:
b[1][2][1]

72

In [29]:
b.ndim

3

In [38]:
b.reshape(2,2,2,3)

array([[[[11, 12, 13],
         [14, 21, 22]],

        [[23, 24, 31],
         [32, 33, 34]]],


       [[[51, 52, 53],
         [54, 61, 62]],

        [[63, 64, 71],
         [72, 73, 74]]]])