In [16]:
import numpy as np
a = np.array([20,30,40,50])
a

array([20, 30, 40, 50])

In [17]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [18]:
a - b

array([20, 29, 38, 47])

In [19]:
b ** 2

array([0, 1, 4, 9])

In [20]:
b ** 3

array([ 0,  1,  8, 27], dtype=int32)

In [21]:
e =10 * np.sin(a) 
e

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [22]:
e < 7

array([False,  True, False,  True])

In [23]:
a * b # elements product

array([  0,  30,  80, 150])

In [24]:
a @ b  

260

In [35]:
a.dot(b)

260

In [39]:
f = np.ones((2,4))
g = np.zeros((2,4))

In [40]:
f

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
g

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
h = np.random.random((4,6))
h

array([[0.11887333, 0.58916084, 0.84399191, 0.99344575, 0.19050205,
        0.81707079],
       [0.62894245, 0.76990303, 0.40037393, 0.19126949, 0.27490039,
        0.19762421],
       [0.12822047, 0.78988106, 0.90006001, 0.26910661, 0.90465274,
        0.16810487],
       [0.37829317, 0.72805887, 0.4040208 , 0.76508456, 0.94713858,
        0.85422274]])

In [49]:
np.sum(b)

6

In [50]:
b.sum()

6

In [51]:
np.min(b)

0

In [53]:
np.max(b)

3

In [54]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356, 1.73205081])