In [1]:
import numpy as np

In [3]:
sayilar = np.arange(0,35,5)
sayilar

array([ 0,  5, 10, 15, 20, 25, 30])

In [4]:
sayilar[0]

0

In [5]:
len(sayilar)

7

In [6]:
sayilar[0:3]

array([ 0,  5, 10])

In [12]:
sayilar = np.arange(0,120,5)
sayilar.shape

(24,)

In [15]:
sayilar = sayilar.reshape(2,3,4)
sayilar

array([[[  0,   5,  10,  15],
        [ 20,  25,  30,  35],
        [ 40,  45,  50,  55]],

       [[ 60,  65,  70,  75],
        [ 80,  85,  90,  95],
        [100, 105, 110, 115]]])

In [16]:
sayilar[1,2,3]

115

In [17]:
sayilar[1][2][3]

115

In [24]:
sayilar[0][1:,1:2]

array([[25],
       [45]])

In [25]:
sayilar[0,1:,1:2]

array([[25],
       [45]])

In [62]:
sayilar[-1,-1,-1]

115