In [9]:
import numpy as np
a = np.floor(10 * np.random.random((3,4)))

In [10]:
a

array([[3., 7., 0., 6.],
       [1., 8., 8., 5.],
       [3., 7., 1., 2.]])

In [11]:
a.shape

(3, 4)

In [18]:
a.ravel()

array([3., 7., 0., 6., 1., 8., 8., 5., 3., 7., 1., 2.])

In [24]:
a

array([[3., 7., 0., 6.],
       [1., 8., 8., 5.],
       [3., 7., 1., 2.]])

In [25]:
a.T

array([[3., 1., 3.],
       [7., 8., 7.],
       [0., 8., 1.],
       [6., 5., 2.]])

In [27]:
a.reshape(2,-1)

array([[3., 7., 0., 6., 1., 8.],
       [8., 5., 3., 7., 1., 2.]])