In [1]:
import numpy as np

In [7]:
a = np.floor(10*np.random.random((2,3)))
b = np.floor(10*np.random.random((2,3)))

In [8]:
a,b

(array([[5., 3., 5.],
        [9., 9., 1.]]),
 array([[7., 2., 8.],
        [6., 3., 1.]]))

In [10]:
c = np.vstack((a,b))
c

array([[5., 3., 5.],
       [9., 9., 1.],
       [7., 2., 8.],
       [6., 3., 1.]])

In [13]:
d = np.hstack((a,b))
d

array([[5., 3., 5., 7., 2., 8.],
       [9., 9., 1., 6., 3., 1.]])