In [17]:
import numpy as np

In [18]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
b = a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b[0] = 27
a

array([27,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [21]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
b = a.copy()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b[0] = 27
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])